### ISSUE TITLE
README links to binary downloads

### ISSUE THREAD

**Issue by sillitoe** [UCLOrengoGroup/cath-tools#13]
Link on main README.md file currently doesn't work:

https://github.com/UCLOrengoGroup/cath-tools/blob/master/tools/cath-superpose

Will investigate in a second...

**Comment by tonyelewis** [comment]
Thanks for flagging this. I remember thinking that I should make these links absolute when I was away from  a computer. I clearly never remembered to actually do it when back in front of a computer.
