### ISSUE TITLE
how to get multiple superpositions with cath-superpose?

### ISSUE THREAD

**Issue by sillitoe** [UCLOrengoGroup/cath-tools#18]
useful to have an example of how cath-superpose can be used to generate multiple superpositions rather than just pairwise (e.g. CATH superfamily superpositions)

**Comment by tonyelewis** [comment]
Good point - thanks. I've added some notes [here](http://cath-tools.readthedocs.io/en/latest/tools/cath-superpose/#multiple-superpositions). Let me know your thoughts if you have suggestions or close this issue if you think it's adequately resolved. Ta.

**Comment by sillitoe** [comment]
Nice! Excellent work, thanks.

**Comment by sillitoe** [comment]
@toluadeyelu - please reopen this ticket if you have any further questions

**Comment by toluadeyelu** [comment]
Thank you @tonyelewis  and @sillitoe for this. I was actually very happy it works and I was able to implement it for superposition of the domains within the CATH-Funfams which am looking at. Thumbs up.

**Comment by tonyelewis** [comment]
Great. I'm glad to hear that - thanks for letting me know.
