### ISSUE TITLE
Run structural comparisons within cath-superpose

### ISSUE THREAD

**Issue by sillitoe** [UCLOrengoGroup/cath-tools#2]
Currently, superposing structures with `cath-superpose` requires that the user has already run the matrix of structure comparisons (SSAP). This is handled by the wrapper script `cath-superpose-multi-temp-script`, however it would be nice if`cath-superpose` could run its own SSAPs (where required).

**Comment by tonyelewis** [comment]
Added (in 3ca670639e8ebf8063c81b178ca77d8fa53667c8, 5df978d17034c59c8aeb5dc6298f1727e68f2b8e and 3e3a076d75b217001b3aaa63518df47a97fc9a9d amongst others).
