### ISSUE TITLE
cath-resolve-hits: parse hmmscan output

### ISSUE THREAD

**Issue by sillitoe** [UCLOrengoGroup/cath-tools#32]
Would be useful to parse hmmscan output directly.

**Comment by tonyelewis** [comment]
Closing for now.

Though it would definitely be a plus, we're not yet aware of any specific users that would actually use it. In particular, it sounds as though the use-case that motivated @sillitoe to open the issue may well not involve using HMMER output after all.

Will re-open this issue if we find anyone that wants it.

**Comment by tonyelewis** [comment]
Reopening this issue for parsing hmmscan output as we do now have a specific user requesting this feature.
