### ISSUE TITLE
Alignment HTML isn't rendering with fixed-width font on chrome

### ISSUE THREAD

**Issue by tonyelewis** [UCLOrengoGroup/cath-tools#36]
It's working on Firefox (and I thought it was previously working on Chrome).

Maybe just change:

~~~
font-family: courier;
~~~

...to something like...

~~~
font-family: courier, monospace;
~~~

**Comment by sillitoe** [comment]
Yup, this fix should work fine.

https://developer.mozilla.org/en/docs/Web/CSS/font-family

**Comment by tonyelewis** [comment]
Thanks for guidance @sillitoe.
