### ISSUE TITLE
Add binaries to a permanent location

### ISSUE THREAD

**Issue by sillitoe** [UCLOrengoGroup/cath-tools#4]
Plan is to get Travis-CI to add binaries to AWS S3 (after a successful build). This issue is here to keep a record of progress.

**Comment by tonyelewis** [comment]
This is now done, eg:
https://cath-tools-built.s3.amazonaws.com/UCLOrengoGroup/cath-tools/89/89.1/release_build/cath-ssap
https://cath-tools-built.s3.amazonaws.com/UCLOrengoGroup/cath-tools/89/89.1/release_build/cath-superpose
https://cath-tools-built.s3.amazonaws.com/UCLOrengoGroup/cath-tools/89/89.1/release_build/cath-refine-align

I have also put static links to those in the front-page README.md.

I'll close this ticket as the binaries now get added to a permanent location.

However it's not a great system at present:
 * the generated directories aren't browsable (and from what I can see it isn't trivial to make them browsable)
 * the builds aren't (directly) connected with the Git commit SHA1s
