### ISSUE TITLE
[dependency: v14.2 onwards] {cath-superpose.ubuntu14.04} libstdc++.so.6: version `GLIBCXX_3.4.22' not found

### ISSUE THREAD

**Issue by shouldsee** [UCLOrengoGroup/cath-tools#42]
Hi there,

I am having some problem get "cath-resolve-hits.ubuntu14.04" to run on my ubuntu.

System: Ubuntu 16.04LTS
apt version: apt 1.2.18 (amd64)

Running 
```sh
./cath-resolve-hits.ubuntu14.04 
```
downloaded from versions newer than [v0.14.2](https://github.com/UCLOrengoGroup/cath-tools/releases/download/v0.14.2/cath-resolve-hits.ubuntu14.04)  raise an exception saying:
```sh
./cath-resolve-hits.ubuntu14.04: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./cath-resolve-hits.ubuntu14.04)
```

I tried update "libstdc++6" without useful results (along with,  "libstdc++6-4.7-dev","libstdc++6-5-dbg")
```sh
sudo apt install libstdc++6
libstdc++6 is already the newest version (5.4.0-6ubuntu1~16.04.4).
libstdc++6-4.7-dev is already the newest version (4.7.4-3ubuntu12).
libstdc++6-5-dbg is already the newest version (5.4.0-6ubuntu1~16.04.4).
```
Although the legacy version from [v0.14.1](https://github.com/UCLOrengoGroup/cath-tools/releases/download/v0.14.1/cath-resolve-hits) works fine without this dependency, I am still wondering how I can install this dependency (for v0.14.2 onwards) on ubuntu quickly?

Kind regards
Feng

**Comment by tonyelewis** [comment]
The short answer to solve your problem now is: use the `.centos6` executable instead.

But thanks for flagging this issue. As you say, the `.ubuntu14.04` builds don't work out-of-the-box on Ubuntu 16.04 for &ge; 0.14.2. They do all work on Ubuntu &ge; 16.10.

I suspect this is to do with my setup for the Travis build using a package repo that pulls in more recent libraries/compilers etc. I'll look into it a bit more...

**Comment by shouldsee** [comment]
@tonyelewis 
The [centos6 version](https://github.com/UCLOrengoGroup/cath-tools/releases/download/v0.14.2/cath-resolve-hits.centos6) indeed worked. Many thanks!

**Comment by tonyelewis** [comment]
The Ubuntu builds should now work on Ubuntu &ge; 14.10 from [v0.15.3](https://github.com/UCLOrengoGroup/cath-tools/releases/tag/v0.15.3) onwards.

@shouldsee, thanks for alerting me to this issue.

**Comment by shouldsee** [comment]
I can have tested that cath-resolve-hits from [v0.15.3](https://github.com/UCLOrengoGroup/cath-tools/releases/tag/v0.15.3) now works with my installation of Ubuntu16.04LTS.

@tonyelewis Thanks for the fix!

**Comment by tonyelewis** [comment]
@shouldsee thanks for testing.
