### ISSUE TITLE
Build time is slow

### ISSUE THREAD

**Issue by anadon** [UCLOrengoGroup/cath-tools#59]
A significant enhancement you should consider is switching the cmake build backend to use ninja.  It makes a pretty big difference.  It is worth it.

**Comment by tonyelewis** [comment]
Thanks for contributing to cath-tools.

I'm not sure `ninja` is *massively* faster than `make` for complete builds (so long as you're using a sensible value for `make`'s `-j [N], --jobs[=N]` option).

But, yes, `ninja` is very much faster for small, incremental (or even no-op) builds.

However, I don't think a project should impose that choice on the user. If anyone building cath-tools prefers `ninja`, they can pass `-GNinja` to `cmake`. That's what I do.
