### ISSUE TITLE
readthedocs build is currently failing (404)

### ISSUE THREAD

**Issue by sillitoe** [UCLOrengoGroup/cath-tools#6]
The readthedocs link currently directs to a 404.
 
Looks like this is because the build is failing with the following error

https://readthedocs.org/projects/cath-tools/builds/3459390/

```
error: [Errno 104] Connection reset by peer
/home/docs/checkouts/readthedocs.org/user_builds/cath-tools/envs/latest/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

Following that suggested link:

https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning

Seems to suggest we need to upgrade to a more recent version of python (v3).

**Comment by tonyelewis** [comment]
Thanks for the report.

**Comment by tonyelewis** [comment]
Hmm. I tried switching to Python 3. That made it break worse. Now that I've switched it back again, the builds seem to be passing. But the page is still a 404. I might come back to this later to see if it just sorts itself out.

**Comment by tonyelewis** [comment]
Seems to be working if I visit the URL with a trailing `/README/`. I don't know why the index isn't working but this will do for now. In the future, I think it'd be good to separate out the README.md in the root directory from ReadTheDocs Markdown files in a separate subdirectory.

**Comment by tonyelewis** [comment]
Have now improved so:
 * the index page works (from an `index.md` file)
 * the ReadTheDocs material is in a separate `docs` subdirectory
 * the *Build* text is less prominent than the *Quickstart* text
