### ISSUE TITLE
Installing Boost >= 1.58 on Ubuntu (16.04)

### ISSUE THREAD

**Issue by sillitoe** [UCLOrengoGroup/cath-tools#63]
The commands in the docs only give me Boost 1.58.

> Boost ( v1.60.0 / v1.61.0 ) 
> [Ubuntu]
> $ sudo apt-get install libboost-all-dev

I'm running Ubuntu 16.04 LTS which doesn't seem crazily old.

```
$ cat /etc/issue
Ubuntu 16.04.4 LTS
```

I guess my options are:
 * upgrade Ubuntu
 * install boost libraries from a different method ([Boost docs](http://www.boost.org/doc/libs/1_64_0/more/getting_started/unix-variants.html) suggest install from tarball)

If that sounds about right (and assuming this project definitely does need boost >= 1.60), I can submit a PR for the docs?

**Comment by tonyelewis** [comment]
That sounds about right. I'm afraid it looks like the Boost jumped to 1.61 in 16.10. Have you tried just building anyway? It's *possible* I haven't actually used anything not it 1.58 (or only in test code). But I wouldn't get my hopes up.

TBH, I just expected that people would not do their own builds very much at all. So I've essentially made Travis-CI's setup my limiting factor for Boosts. To improve my user understanding, what is your situation that causes you to want to build yourself?

Yep - if you can be bothered to update the docs (maybe add a note after the relevant part like: if you're OS isn't sparkling new (eg older that Ubuntu 16.10) then the OS-supplied Boost may be too old so you may need to install a newer one directly from the Boost website instead), that'd be great. You really don't need to do a PR; if you update directly, I'll see the change and can tweak if I see fit.

**Comment by sillitoe** [comment]
Thanks.

My user case is that I'm investigating #62  :)

**Comment by tonyelewis** [comment]
> My user case is that I'm investigating #62 :)

Thanks very much.

Maybe try rsyncing from my `~/cath-tools`? I've just pulled (but not rebuilt the very latest change). I have six builds:

~~~
ninja_clang_debug_shared/cath-ssap
ninja_clang_release/cath-ssap
ninja_clang_relwithdebinfo/cath-ssap
ninja_gcc_debug_shared/cath-ssap
ninja_gcc_release/cath-ssap
ninja_gcc_relwithdebinfo/cath-ssap
~~~
