### ISSUE TITLE
Add regression test for overall performance (ROC)

### ISSUE THREAD

**Issue by sillitoe** [UCLOrengoGroup/cath-tools#9]
It would be useful to have a regression test to check whether a code change has made an adverse affect on the algorithm's performance. 

Presumably this test would take a long time to run so wouldn't be part of the regular build. Also, it may require some manual analysis (e.g. comparing ROC graphs).

Has this already been set up? If so, this might just be a case of adding some internal docs (point me in the right direction and I'll write it up).

**Comment by tonyelewis** [comment]
I've:
 * created a new [cath-tools-supplementary](https://github.com/UCLOrengoGroup/cath-tools-supplementary) repo,
 * move some stuff over there from here and
 * put a new [homologue_discrimination_benchmark](https://github.com/UCLOrengoGroup/cath-tools-supplementary/tree/master/homologue_discrimination_benchmark) directory to fulfil the requirements of this issue.
